# Generated by Django 4.1.7 on 2023-03-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_contactform_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
    ]
