# Generated by Django 4.1.7 on 2023-03-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_popup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popup',
            old_name='number',
            new_name='phone',
        ),
    ]
